# Generated by Django 5.1.1 on 2024-10-05 12:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Lesson",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "subject",
                    models.CharField(
                        choices=[
                            ("exoplanets_types", "Exoplanet Types"),
                            ("exoplanets_discovery", "Exoplanet Discovery"),
                            ("exoplanets_habitability", "Exoplanet Habitability"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "grade_level",
                    models.CharField(
                        choices=[
                            ("elementary_school", "Elementary School"),
                            ("middle_school", "Middle School"),
                            ("high_school", "High School"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "class_size",
                    models.PositiveIntegerField(
                        choices=[
                            (10, "Up to 10 students"),
                            (30, "10 - 30 students"),
                            (50, "More than 30 students"),
                        ]
                    ),
                ),
                (
                    "technology_access",
                    models.CharField(
                        choices=[
                            ("unavailable", "No technology available (offline)"),
                            ("limited", "Limited access"),
                            ("full", "Full access"),
                        ],
                        max_length=100,
                    ),
                ),
                (
                    "class_length",
                    models.PositiveIntegerField(
                        choices=[
                            (30, "30 minutes"),
                            (45, "45 minutes"),
                            (90, "90 minutes"),
                        ]
                    ),
                ),
                (
                    "learning_styles",
                    models.CharField(
                        choices=[
                            ("visual", "Visual"),
                            ("auditory", "Auditory"),
                            ("kinesthetic", "Kinesthetic"),
                        ],
                        max_length=100,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_lesson",
                    models.TextField(
                        help_text="The output of a web scraping process generated by AI"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lessons",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
