# Generated by Django 5.1.1 on 2024-10-05 12:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("lesson", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lesson",
            name="class_size",
            field=models.PositiveIntegerField(
                choices=[
                    (10, "5 - 10 students"),
                    (20, "10 - 20 students"),
                    (50, "20 - 50 students"),
                ]
            ),
        ),
    ]
