# Generated by Django 5.1.1 on 2024-10-05 14:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("lesson", "0002_alter_lesson_class_size"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lesson",
            name="created_lesson",
            field=models.TextField(
                blank=True,
                help_text="The output of a web scraping process generated by AI",
                null=True,
            ),
        ),
    ]
