// !! Careful if you edit this file as it will modify all other pages in the project that don't have a layout.tsx file

import type { Metadata } from "next";
import "./globals.css";
import Header from "@/app/components/header/Header";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`antialiased flex flex-col min-h-screen text-white`}>
        <Header />
        <div className="px-5">{children}</div>
      </body>
    </html>
  );
}
