# Generated by Django 5.1.1 on 2024-10-06 18:10

import user.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="avatar",
            field=models.ImageField(
                blank=True, null=True, upload_to=user.models.get_user_directory_path
            ),
        ),
    ]
