from django.db import models
from django.contrib.auth import get_user_model


User = get_user_model()

# Create your models here.
class Lesson(models.Model):
    
    GRADE_LEVEL = [
        ('elementary_school', 'Elementary School'),
        ('middle_school', 'Middle School'),
        ('high_school', 'High School'),
    ]

    TOPICS_OF_INTEREST = [
        ('exoplanets_types', 'Exoplanet Types'),
        ('exoplanets_discovery', 'Exoplanet Discovery'),
        ('exoplanets_habitability', 'Exoplanet Habitability')
    ]

    PREFERRED_LEARNING_STYLES = [
        ('visual', 'Visual'),
        ('auditory', 'Auditory'),
        ('kinesthetic', 'Kinesthetic')
    ]

    TECHNOLOGY_ACCESS = [
        ('unavailable', 'No technology available (offline)'),
        ('limited', 'Limited access'),
        ('full', 'Full access')
    ]

    CLASS_SIZE = [
        (10, '5 - 10 students'),
        (20, '10 - 20 students'),
        (50, '20 - 50 students')
    ]

    CLASS_LENGHT = [
        (30, '30 minutes'),
        (45, '45 minutes'),
        (90, '90 minutes')
    ]
    
    subject = models.CharField(max_length=50, choices=TOPICS_OF_INTEREST)
    grade_level = models.CharField(max_length=20, choices=GRADE_LEVEL)
    class_size = models.PositiveIntegerField(choices=CLASS_SIZE)  
    technology_access = models.CharField(max_length=100, choices=TECHNOLOGY_ACCESS)
    class_length = models.PositiveIntegerField(choices=CLASS_LENGHT) 
    learning_styles = models.CharField(max_length=100, choices=PREFERRED_LEARNING_STYLES)
    created_at = models.DateTimeField(auto_now_add=True)
    created_lesson = models.TextField(blank=True, null=True,help_text="The output of a web scraping process generated by AI")
    user = models.ForeignKey(to=User, on_delete=models.CASCADE, related_name="lessons")

    def __str__(self):
        return f"Lesson {self.id}: {self.subject} ({self.grade_level})"

