# Generated by Django 5.1.1 on 2024-10-05 11:34

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("article", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="article",
            name="favourited_by",
            field=models.ManyToManyField(
                blank=True,
                null=True,
                related_name="favorite_resources",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
