# Generated by Django 5.1.1 on 2025-02-25 15:11

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='favourited_by',
            field=models.ManyToManyField(blank=True, related_name='favorite_resources', to=settings.AUTH_USER_MODEL),
        ),
    ]
